# define the hosts
dhil.lib.sfu.ca:
     stage: dhil
     become: lim
     deploy_path: /var/www/lim
     user: mjoyce

# The settings key must start with a dot(.) to prevent it being treated as
# a host in the inventory.
.settings:
    application: lim
    repository: https://github.com/ubermichael/lim.git
    branch: main
    shared_files:
        - .env.local
    shared_dirs:
        - var/log
        - var/sessions
        - public/images/blog
    writable_dirs:
        - var/log
        - var/sessions
        - var/cache
        - ../../shared/public/images/blog
    composer_options: 'install --no-progress --optimize-autoloader --no-interaction'
    site_path: /lim
    context: system_u:object_r:httpd_sys_rw_content_t:s0
